# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SerializedListNew.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='SerializedListNew.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x17SerializedListNew.proto\"\xbb\x01\n\x11SerializedListNew\x12,\n\x08\x45lements\x18\x01 \x03(\x0b\x32\x1a.SerializedListNew.Element\x1aT\n\x07\x45lement\x12\r\n\x05score\x18\x01 \x02(\x05\x12\r\n\x05\x64ocId\x18\x02 \x02(\t\x12+\n\x03typ\x18\x03 \x02(\x0e\x32\x1e.SerializedListNew.AnchorsType\"\"\n\x0b\x41nchorsType\x12\x05\n\x01r\x10\x00\x12\x05\n\x01\x61\x10\x01\x12\x05\n\x01\x62\x10\x02')
)



_SERIALIZEDLISTNEW_ANCHORSTYPE = _descriptor.EnumDescriptor(
  name='AnchorsType',
  full_name='SerializedListNew.AnchorsType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='r', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='a', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='b', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=181,
  serialized_end=215,
)
_sym_db.RegisterEnumDescriptor(_SERIALIZEDLISTNEW_ANCHORSTYPE)


_SERIALIZEDLISTNEW_ELEMENT = _descriptor.Descriptor(
  name='Element',
  full_name='SerializedListNew.Element',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='score', full_name='SerializedListNew.Element.score', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='docId', full_name='SerializedListNew.Element.docId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='typ', full_name='SerializedListNew.Element.typ', index=2,
      number=3, type=14, cpp_type=8, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=179,
)

_SERIALIZEDLISTNEW = _descriptor.Descriptor(
  name='SerializedListNew',
  full_name='SerializedListNew',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='Elements', full_name='SerializedListNew.Elements', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SERIALIZEDLISTNEW_ELEMENT, ],
  enum_types=[
    _SERIALIZEDLISTNEW_ANCHORSTYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=215,
)

_SERIALIZEDLISTNEW_ELEMENT.fields_by_name['typ'].enum_type = _SERIALIZEDLISTNEW_ANCHORSTYPE
_SERIALIZEDLISTNEW_ELEMENT.containing_type = _SERIALIZEDLISTNEW
_SERIALIZEDLISTNEW.fields_by_name['Elements'].message_type = _SERIALIZEDLISTNEW_ELEMENT
_SERIALIZEDLISTNEW_ANCHORSTYPE.containing_type = _SERIALIZEDLISTNEW
DESCRIPTOR.message_types_by_name['SerializedListNew'] = _SERIALIZEDLISTNEW
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SerializedListNew = _reflection.GeneratedProtocolMessageType('SerializedListNew', (_message.Message,), dict(

  Element = _reflection.GeneratedProtocolMessageType('Element', (_message.Message,), dict(
    DESCRIPTOR = _SERIALIZEDLISTNEW_ELEMENT,
    __module__ = 'SerializedListNew_pb2'
    # @@protoc_insertion_point(class_scope:SerializedListNew.Element)
    ))
  ,
  DESCRIPTOR = _SERIALIZEDLISTNEW,
  __module__ = 'SerializedListNew_pb2'
  # @@protoc_insertion_point(class_scope:SerializedListNew)
  ))
_sym_db.RegisterMessage(SerializedListNew)
_sym_db.RegisterMessage(SerializedListNew.Element)


# @@protoc_insertion_point(module_scope)
