# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DictionaryWithTitle.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DictionaryWithTitle.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  serialized_pb=_b('\n\x19\x44ictionaryWithTitle.proto\"\xc8\x03\n\x04\x44ico\x12\x11\n\tPageTitle\x18\x01 \x02(\t\x12\x16\n\x0elength_anchors\x18\x02 \x02(\x05\x12\x11\n\tPageViews\x18\x03 \x02(\x02\x12\x10\n\x08PageRank\x18\x04 \x02(\x02\x12)\n\nOrgAnchors\x18\x05 \x03(\x0b\x32\x15.Dico.OrgAnchorsEntry\x12#\n\x07\x41nchors\x18\x06 \x03(\x0b\x32\x12.Dico.AnchorsEntry\x12)\n\nCategories\x18\x07 \x03(\x0b\x32\x15.Dico.CategoriesEntry\x12+\n\x0b\x43\x61lledPages\x18\x08 \x03(\x0b\x32\x16.Dico.CalledPagesEntry\x1a\x31\n\x0fOrgAnchorsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a.\n\x0c\x41nchorsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x31\n\x0f\x43\x61tegoriesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x1a\x32\n\x10\x43\x61lledPagesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01')
)




_DICO_ORGANCHORSENTRY = _descriptor.Descriptor(
  name='OrgAnchorsEntry',
  full_name='Dico.OrgAnchorsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Dico.OrgAnchorsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Dico.OrgAnchorsEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=286,
  serialized_end=335,
)

_DICO_ANCHORSENTRY = _descriptor.Descriptor(
  name='AnchorsEntry',
  full_name='Dico.AnchorsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Dico.AnchorsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Dico.AnchorsEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=337,
  serialized_end=383,
)

_DICO_CATEGORIESENTRY = _descriptor.Descriptor(
  name='CategoriesEntry',
  full_name='Dico.CategoriesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Dico.CategoriesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Dico.CategoriesEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=385,
  serialized_end=434,
)

_DICO_CALLEDPAGESENTRY = _descriptor.Descriptor(
  name='CalledPagesEntry',
  full_name='Dico.CalledPagesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Dico.CalledPagesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Dico.CalledPagesEntry.value', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=436,
  serialized_end=486,
)

_DICO = _descriptor.Descriptor(
  name='Dico',
  full_name='Dico',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='PageTitle', full_name='Dico.PageTitle', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length_anchors', full_name='Dico.length_anchors', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PageViews', full_name='Dico.PageViews', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='PageRank', full_name='Dico.PageRank', index=3,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='OrgAnchors', full_name='Dico.OrgAnchors', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Anchors', full_name='Dico.Anchors', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='Categories', full_name='Dico.Categories', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='CalledPages', full_name='Dico.CalledPages', index=7,
      number=8, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_DICO_ORGANCHORSENTRY, _DICO_ANCHORSENTRY, _DICO_CATEGORIESENTRY, _DICO_CALLEDPAGESENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=486,
)

_DICO_ORGANCHORSENTRY.containing_type = _DICO
_DICO_ANCHORSENTRY.containing_type = _DICO
_DICO_CATEGORIESENTRY.containing_type = _DICO
_DICO_CALLEDPAGESENTRY.containing_type = _DICO
_DICO.fields_by_name['OrgAnchors'].message_type = _DICO_ORGANCHORSENTRY
_DICO.fields_by_name['Anchors'].message_type = _DICO_ANCHORSENTRY
_DICO.fields_by_name['Categories'].message_type = _DICO_CATEGORIESENTRY
_DICO.fields_by_name['CalledPages'].message_type = _DICO_CALLEDPAGESENTRY
DESCRIPTOR.message_types_by_name['Dico'] = _DICO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Dico = _reflection.GeneratedProtocolMessageType('Dico', (_message.Message,), dict(

  OrgAnchorsEntry = _reflection.GeneratedProtocolMessageType('OrgAnchorsEntry', (_message.Message,), dict(
    DESCRIPTOR = _DICO_ORGANCHORSENTRY,
    __module__ = 'DictionaryWithTitle_pb2'
    # @@protoc_insertion_point(class_scope:Dico.OrgAnchorsEntry)
    ))
  ,

  AnchorsEntry = _reflection.GeneratedProtocolMessageType('AnchorsEntry', (_message.Message,), dict(
    DESCRIPTOR = _DICO_ANCHORSENTRY,
    __module__ = 'DictionaryWithTitle_pb2'
    # @@protoc_insertion_point(class_scope:Dico.AnchorsEntry)
    ))
  ,

  CategoriesEntry = _reflection.GeneratedProtocolMessageType('CategoriesEntry', (_message.Message,), dict(
    DESCRIPTOR = _DICO_CATEGORIESENTRY,
    __module__ = 'DictionaryWithTitle_pb2'
    # @@protoc_insertion_point(class_scope:Dico.CategoriesEntry)
    ))
  ,

  CalledPagesEntry = _reflection.GeneratedProtocolMessageType('CalledPagesEntry', (_message.Message,), dict(
    DESCRIPTOR = _DICO_CALLEDPAGESENTRY,
    __module__ = 'DictionaryWithTitle_pb2'
    # @@protoc_insertion_point(class_scope:Dico.CalledPagesEntry)
    ))
  ,
  DESCRIPTOR = _DICO,
  __module__ = 'DictionaryWithTitle_pb2'
  # @@protoc_insertion_point(class_scope:Dico)
  ))
_sym_db.RegisterMessage(Dico)
_sym_db.RegisterMessage(Dico.OrgAnchorsEntry)
_sym_db.RegisterMessage(Dico.AnchorsEntry)
_sym_db.RegisterMessage(Dico.CategoriesEntry)
_sym_db.RegisterMessage(Dico.CalledPagesEntry)


_DICO_ORGANCHORSENTRY._options = None
_DICO_ANCHORSENTRY._options = None
_DICO_CATEGORIESENTRY._options = None
_DICO_CALLEDPAGESENTRY._options = None
# @@protoc_insertion_point(module_scope)
